; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Seed Adventure Installer
; Created by Vibhav / Vibgamer0137

[Setup]
AppId={{8B4F5C21-6E3A-4B5F-9D71-SEEDADVENTURE}}
AppName=Seed Adventure
AppVersion=1.0
AppVerName=Seed Adventure 1.0
AppPublisher=Vibgamer0137 (Vibhav)

DefaultDirName={autopf}\Seed Adventure
DefaultGroupName=Seed Adventure

OutputDir=Output
OutputBaseFilename=SeedAdventure-1.0-Setup

SetupIconFile=Assets\Images\Supported types\icon.ico
UninstallDisplayIcon={app}\SeedAdventure.exe

Compression=lzma
SolidCompression=yes

WizardStyle=modern

[Files]
Source: "dist\SeedAdventure.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "Assets\*"; DestDir: "{app}\Assets"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\Seed Adventure"; Filename: "{app}\SeedAdventure.exe"
Name: "{autodesktop}\Seed Adventure"; Filename: "{app}\SeedAdventure.exe"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Create a desktop shortcut"; GroupDescription: "Additional icons:"

[Run]
Filename: "{app}\SeedAdventure.exe"; Description: "Launch Seed Adventure"; Flags: nowait postinstall skipifsilent